export const MenuConstants = {
  dashboard: "Dashboard",
  transaction: "Transaction",
  uploadPrimarySales: "Upload Primary Sales",
  uploadSecondary: "Upload Secondary",
  uploadStockAdjustment: "Upload Stock Adjustment",
  target: "Target",
  download: "Download",
  transactionReturn: "Transaction Return",
  submenu1: "Submenu 1",
  submenu2: "Submenu 2",
  ispIncentive: "ISP Incentive",
  nofileselected: "No File Selected",
  file: "File",
  choose: "Choose",
  Scheme: "Scheme",
  payout: "Payout",
  details: "Details",
  merchandizing: "Merchandizing",
  taskCategoryMaster: "Task Category Master",
  manageTask: "Manage Task",
  updateTask: "Update Task",
  competition: "Competition",
  submenucompetetion1: "Competition Submenu 1",
  submenucompetetion2: "Competition Submenu 2",
  learningAndDevelopment: "Learning & Development",
  manageCategory: "Manage L & D Category",
  manageContent: "Manage L & D Content",
  manageAssessment: "Manage Assessment",
  survey: "Survey",
  country: "Country",
  region: "Region",
  state: "State",
  city: "City",
  area: "Area",
  bulkUpload: "Bulk Upload",
  pincode: "Pincode",
  feedback: "Feedback",
  view: "View",
  upload: "  Upload",
  SKU: "SKU",
  wise: "Wise",
  page: "Page",
  showall: "Show All",
  reports: "Reports",
  bulletin: "Bulletin",
  action: "Action",
  create: "Create",
  cancel: "Cancel",
  search: "Search",
  list: "List",
  master: "Master",
  name: "Name",
  code: "Code",
  description: "Description",
  brand: "Brand",
  category: "Category",
  subCategory: "Subcategory",
  subCategoryclassification: "Subcategory/ classification",
  model: "Model",
  manageBullettinCategory: "Manage Bulletin Category",
  manageBulletin: "Manage Bulletin",
  manage: "Manage",
  masterSetting: "Setting / Master",
  location: "Location",
  product: "Product",
  retailer: "Retailer",
  salesChannel: "Sales channel",
  userMaster: "User Master",
  price: "Price",
  leaveMaster: "Leave Master",
  ispMaster: "ISP Master",
  manageSalesChannel: "Manage sales channel",
  spare: "Spare",
  warrantyVoidReason: "Warranty void reason",
  userMasters: "User Masters",
  bulkUploadMapping: "Bulk Upload Mapping",
  priceGroup: "Price Group",
  manageLeaveTypes: "Manage Leave Types",
  leaveAllocation: "Leave Allocation",
  ISPmaster: "ISP Master",
  manageISP: "Manage ISP",
  preBookingSKU: "Pre-booking SKU",
  rankingWeightage: "Ranking Weightage",
};
